CREATE TABLE IF NOT EXISTS `ip_employees` (
  `employee_id` INT(11) NOT NULL AUTO_INCREMENT,
  `company_id` INT(11) NOT NULL DEFAULT 1,
  `user_id` INT(11) NULL DEFAULT NULL,
  `employee_number` VARCHAR(50) NOT NULL,
  `first_name` VARCHAR(100) NOT NULL,
  `last_name` VARCHAR(100) DEFAULT '',
  `gender` VARCHAR(20) DEFAULT '',
  `birth_date` DATE NULL DEFAULT NULL,
  `birth_place` VARCHAR(100) DEFAULT '',
  `national_id` VARCHAR(50) DEFAULT '',
  `email` VARCHAR(100) NOT NULL,
  `phone` VARCHAR(50) DEFAULT '',
  `mobile` VARCHAR(50) DEFAULT '',
  `address_1` VARCHAR(255) DEFAULT '',
  `address_2` VARCHAR(255) DEFAULT '',
  `city` VARCHAR(100) DEFAULT '',
  `state` VARCHAR(100) DEFAULT '',
  `zip_code` VARCHAR(20) DEFAULT '',
  `country` VARCHAR(100) DEFAULT '',
  `department` VARCHAR(100) DEFAULT '',
  `job_title` VARCHAR(100) DEFAULT '',
  `employment_status` VARCHAR(50) DEFAULT 'full_time',
  `join_date` DATE NULL DEFAULT NULL,
  `active` TINYINT(1) NOT NULL DEFAULT 1,
  `bank_name` VARCHAR(100) DEFAULT '',
  `bank_account_number` VARCHAR(50) DEFAULT '',
  `bank_account_holder` VARCHAR(100) DEFAULT '',
  `tax_id` VARCHAR(50) DEFAULT '',
  `notes` TEXT DEFAULT NULL,
  `date_created` DATETIME NOT NULL,
  `date_modified` DATETIME NOT NULL,
  PRIMARY KEY (`employee_id`),
  UNIQUE KEY `employee_number` (`employee_number`),
  KEY `company_id` (`company_id`),
  KEY `user_id` (`user_id`),
  KEY `email` (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
