CREATE TABLE IF NOT EXISTS `ip_reimbursements` (
  `reimbursement_id` INT(11) NOT NULL AUTO_INCREMENT,
  `reimbursement_number` VARCHAR(50) NOT NULL,
  `company_id` INT(11) DEFAULT 1,
  `user_id` INT(11) NOT NULL,
  `employee_id` INT(11) DEFAULT NULL,
  `reimbursement_title` VARCHAR(255) NOT NULL,
  `reimbursement_date` DATE NOT NULL,
  `category` VARCHAR(100) NOT NULL DEFAULT 'Lain-lain',
  `amount` DECIMAL(20,2) NOT NULL DEFAULT 0.00,
  `description` TEXT DEFAULT NULL,
  `attachment` VARCHAR(255) DEFAULT NULL,
  `status` VARCHAR(25) NOT NULL DEFAULT 'pending',
  `approved_by_user_id` INT(11) DEFAULT NULL,
  `approved_at` DATETIME DEFAULT NULL,
  `admin_notes` TEXT DEFAULT NULL,
  `payment_date` DATE DEFAULT NULL,
  `payment_method` VARCHAR(100) DEFAULT NULL,
  `date_created` DATETIME NOT NULL,
  `date_modified` DATETIME NOT NULL,
  PRIMARY KEY (`reimbursement_id`),
  UNIQUE KEY `reimbursement_number` (`reimbursement_number`),
  KEY `company_id` (`company_id`),
  KEY `user_id` (`user_id`),
  KEY `employee_id` (`employee_id`),
  KEY `status` (`status`),
  KEY `reimbursement_date` (`reimbursement_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
